# Generated by Django 6.0.2 on 2026-02-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.CharField(blank=True, help_text="Hint to show user about what to use (e.g., 'Use a for loop')", max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='required_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords required in code (e.g., for,range,print)', max_length=500),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='submitted_code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='expected_output',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topic',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topicprogress',
            name='is_unlocked',
            field=models.BooleanField(default=True),
        ),
    ]
